// <auto-generated />
using System;
using EPostaGonderimApp.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EPostaGonderimApp.DAL.Migrations
{
    [DbContext(typeof(EPostaGonderimContext))]
    [Migration("20240317233916_update1")]
    partial class update1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EPostaGonderimApp.EntityLayer.Entities.EPosta", b =>
                {
                    b.Property<int>("EPostaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EPostaAdresID")
                        .HasColumnType("int");

                    b.Property<bool>("GonderimDurumu")
                        .HasColumnType("bit");

                    b.Property<DateTime>("GonderimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Konu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EPostaID");

                    b.HasIndex("EPostaAdresID");

                    b.ToTable("EPostalar");
                });

            modelBuilder.Entity("EPostaGonderimApp.EntityLayer.Entities.EPostaAdres", b =>
                {
                    b.Property<int>("EPostaAdresID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailSunucuAdres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Port")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EPostaAdresID");

                    b.ToTable("EPostaAdresleri");
                });

            modelBuilder.Entity("EPostaGonderimApp.EntityLayer.Entities.Kisi", b =>
                {
                    b.Property<int>("KisiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CepTelefonu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cinsiyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("EPostaAdresi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvTelefonu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsYeriAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unvan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KisiID");

                    b.ToTable("Kisiler");
                });

            modelBuilder.Entity("EPostaKisi", b =>
                {
                    b.Property<int>("EPostalarEPostaID")
                        .HasColumnType("int");

                    b.Property<int>("KisilerKisiID")
                        .HasColumnType("int");

                    b.HasKey("EPostalarEPostaID", "KisilerKisiID");

                    b.HasIndex("KisilerKisiID");

                    b.ToTable("EPostaKisi");
                });

            modelBuilder.Entity("EPostaGonderimApp.EntityLayer.Entities.EPosta", b =>
                {
                    b.HasOne("EPostaGonderimApp.EntityLayer.Entities.EPostaAdres", "EPostaAdres")
                        .WithMany("EPostalar")
                        .HasForeignKey("EPostaAdresID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EPostaAdres");
                });

            modelBuilder.Entity("EPostaKisi", b =>
                {
                    b.HasOne("EPostaGonderimApp.EntityLayer.Entities.EPosta", null)
                        .WithMany()
                        .HasForeignKey("EPostalarEPostaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EPostaGonderimApp.EntityLayer.Entities.Kisi", null)
                        .WithMany()
                        .HasForeignKey("KisilerKisiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EPostaGonderimApp.EntityLayer.Entities.EPostaAdres", b =>
                {
                    b.Navigation("EPostalar");
                });
#pragma warning restore 612, 618
        }
    }
}
